# Tcl package index file, version 1.0
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded BLT 8.0 [list tclPkgSetup $dir BLT 8.0 {{blt80.dll load {::blt::barchart ::blt::bgexec ::blt::bitmap ::blt::bltdebug ::blt::drag&drop ::blt::graph ::blt::htext ::blt::piechart ::blt::spline ::blt::table ::blt::tilebutton ::blt::tilecheckbutton ::blt::tileframe ::blt::tilelabel ::blt::tileradiobutton ::blt::tilescrollbar ::blt::tiletoplevel ::blt::vector ::blt::watch}} {library/bltGraph.tcl source {BltActivateLegend BltAddBindTag BltBox BltFindElement BltFlashPoint BltGetCoords BltMarkPoint BltPopZoom BltPushZoom BltRemoveBindTag BltResetZoom BltSetZoomPoint BltZoomTitleLast BltZoomTitleNext Blt_ActiveLegend Blt_ClosestPoint Blt_Crosshairs Blt_PrintKey Blt_ZoomStack}} {dd_protocols/dd-color.tcl source dd_send_color} {dd_protocols/dd-file.tcl source dd_send_file} {dd_protocols/dd-number.tcl source dd_send_number} {dd_protocols/dd-text.tcl source dd_send_text}}]

